name: quicksort-react-build
run-name: quicksort-react-build run by ${{ github.actor }}
on:
  workflow_dispatch:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.13.1
      - name: Install npm dependencies
        run: npm install
        working-directory: ./quicksort-react
      - name: Build
        run: npm run build
        working-directory: ./quicksort-react
      - name: Zip
        run: zip -qq -r quicksort-react.zip .next # -x ".next/cache/*"
        working-directory: ./quicksort-react

