name: quicksort-react-build
run-name: quicksort-react-build run by ${{ github.actor }}
on:
  workflow_dispatch:
    branches: [ "main" ]
env:
  S3_BUCKET_NAME : "quicksort-react-bucket"
  AWS_REGION : "ap-southeast-2"
  WORKING_DIR : "./quicksort-react"
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.13.1
      - name: Install npm dependencies
        run: npm install
        working-directory: ${{ env.WORKING_DIR }}
      - name: Build
        run: npm run build
        working-directory: ${{ env.WORKING_DIR }}
      - name: Clean dependencies
        run: npm prune --omit=dev
        working-directory: ${{ env.WORKING_DIR }}
      - name: Zip
        run: zip -qq -r quicksort-react.zip ./.next ./node_modules ./package.json ./package-lock.json
        working-directory: ${{ env.WORKING_DIR }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::508298911387:role/GitHubActionsRole
          aws-region: ${{ env.AWS_REGION }}
      - name: Push zip to S3 bucket
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          aws s3 cp ./quicksort-react.zip s3://${{ env.S3_BUCKET_NAME }}/
